default:
  data:
    mode: remote
    local: "path_for_data_on_your_disk"
    remote: "https://nextcloud.inrae.fr/s/QJS9kxkTPT5fdF5"
    write_results: false
  climato:
    drias:
      url: https://climatedata.umr-cnrm.fr/public/dcsc/projects/DRIAS
      folders: ["DRIAS2020_NEW", "EXPLORE2-Atmos_NEW"]
      ignore_pattern:
        - CNRM-CERFACS-CNRM-CM5/KNMI-RACMO22E,
        - IPSL-IPSL-CM5A-MR/IPSL-WRF381P
      excluded_files:
        - MPI-M-MPI-ESM-LR_CLMcom-CCLM4-8-17_rcp26.nc
        - CNRM-CERFACS-CNRM-CM5_MOHC-HadREM3-GA7-05_rcp85.nc
      variables: ["tas", "tasmax", "tasmin", "huss", "prtot", "sfcWind", "rlds", "rsds"]
      method: "ADAMONT"
